[package]
name = "red-monkey"
version = "0.1.0"
authors = ["AjithPanneerselvam <ajithpanneerselvam20@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
envy = "0.4"
serde = "1.0.117"
serde_derive = "1.0.117"
log  = "0.4.11"
env_logger = "0.8.1"
#redis = "0.18.0"
#r2d2_redis="0.13.0"
redis = { git = "https://github.com/AjithPanneerselvam/redis-rs.git", branch="add-recv-raw-response"}
r2d2_redis = { git = "https://github.com/AjithPanneerselvam/r2d2-redis.git", branch="use-my-redis-branch"}
futures = "0.3.8"
chashmap = "2.2.0"

[[example]]
name = "cmd"
